INSERT INTO airports (code, city)
VALUES
    ('LHR', 'London'),
    ('CDG', 'Paris'),
    ('FRA', 'Frankfurt'),
    ('AMS', 'Amsterdam'),
    ('MAD', 'Madrid'),
    ('FCO', 'Rome'),
    ('BCN', 'Barcelona'),
    ('IST', 'Istanbul'),
    ('MUC', 'Munich'),
    ('CPH', 'Copenhagen'),
    ('ZRH', 'Zurich'),
    ('ATH', 'Athens'),
    ('DUB', 'Dublin'),
    ('OSL', 'Oslo'),
    ('HEL', 'Helsinki'),
    ('STO', 'Stockholm'),
    ('BRU', 'Brussels'),
    ('VIE', 'Vienna'),
    ('PRG', 'Prague'),
    ('WAW', 'Warsaw'),
    ('BUD', 'Budapest'),
    ('LIS', 'Lisbon'),
    ('MXP', 'Milan'),
    ('EDI', 'Edinburgh'),
    ('HAM', 'Hamburg'),
    ('TXL', 'Berlin'),
    ('LGW', 'London Gatwick'),
    ('MAN', 'Manchester'),
    ('ARN', 'Stockholm Arlanda'),
    ('DME', 'Moscow Domodedovo'),
    ('SVO', 'Moscow Sheremetyevo'),
    ('LED', 'St. Petersburg'),
    ('AYT', 'Antalya'),
    ('RIX', 'Riga'),
    ('GVA', 'Geneva'),
    ('NCE', 'Nice'),
    ('SIN', 'Singapore'),
    ('DXB', 'Dubai'),
    ('HKG', 'Hong Kong'),
    ('JFK', 'New York'),
    ('ORD', 'Chicago'),
    ('LAX', 'Los Angeles'),
    ('SFO', 'San Francisco'),
    ('DFW', 'Dallas'),
    ('ATL', 'Atlanta'),
    ('DEN', 'Denver'),
    ('LAS', 'Las Vegas'),
    ('MCO', 'Orlando'),
    ('SEA', 'Seattle'),
    ('PHX', 'Phoenix'),
    ('MIA', 'Miami'),
    ('EWR', 'Newark'),
    ('YYZ', 'Toronto')