INSERT INTO airports (code, city)
VALUES
    ('LHR', 'London'),
    ('CDG', 'Paris'),
    ('FRA', 'Frankfurt'),
    ('AMS', 'Amsterdam'),
    ('MAD', 'Madrid'),
    ('FCO', 'Rome'),
    ('BCN', 'Barcelona'),
    ('IST', 'Istanbul'),
    ('MUC', 'Munich'),
    ('CPH', 'Copenhagen'),
    ('ZRH', 'Zurich'),
    ('ATH', 'Athens'),
    ('DUB', 'Dublin'),
    ('OSL', 'Oslo'),
    ('HEL', 'Helsinki'),
    ('STO', 'Stockholm'),
    ('BRU', 'Brussels'),
    ('VIE', 'Vienna'),
    ('PRG', 'Prague'),
    ('WAW', 'Warsaw'),
    ('BUD', 'Budapest'),
    ('LIS', 'Lisbon'),
    ('MXP', 'Milan'),
    ('EDI', 'Edinburgh'),
    ('HAM', 'Hamburg'),
    ('TXL', 'Berlin'),
    ('LGW', 'London Gatwick'),
    ('MAN', 'Manchester'),
    ('ARN', 'Stockholm Arlanda'),
    ('DME', 'Moscow Domodedovo'),
    ('SVO', 'Moscow Sheremetyevo'),
    ('LED', 'St. Petersburg'),
    ('AYT', 'Antalya'),
    ('RIX', 'Riga'),
    ('GVA', 'Geneva'),
    ('NCE', 'Nice'),
    ('SIN', 'Singapore'),
    ('DXB', 'Dubai'),
    ('HKG', 'Hong Kong'),
    ('JFK', 'New York'),
    ('ORD', 'Chicago'),
    ('LAX', 'Los Angeles'),
    ('SFO', 'San Francisco'),
    ('DFW', 'Dallas'),
    ('ATL', 'Atlanta'),
    ('DEN', 'Denver'),
    ('LAS', 'Las Vegas'),
    ('MCO', 'Orlando'),
    ('SEA', 'Seattle'),
    ('PHX', 'Phoenix'),
    ('MIA', 'Miami'),
    ('EWR', 'Newark'),
    ('YYZ', 'Toronto'),
    ('CDG', 'Paris Charles de Gaulle'),
    ('FRA', 'Frankfurt am Main'),
    ('AMS', 'Amsterdam Schiphol'),
    ('BCN', 'Barcelona El Prat'),
    ('MUC', 'Munich Franz Josef Strauss'),
    ('ORY', 'Paris Orly'),
    ('FCO', 'Rome Leonardo da Vinci'),
    ('CUN', 'Cancun'),
    ('MCO', 'Orlando International'),
    ('TPA', 'Tampa'),
    ('MDW', 'Chicago Midway'),
    ('HND', 'Tokyo Haneda'),
    ('NRT', 'Tokyo Narita'),
    ('PEK', 'Beijing Capital'),
    ('PVG', 'Shanghai Pudong'),
    ('SZX', 'Shenzhen Bao an'),
    ('CAN', 'Guangzhou Baiyun'),
    ('CTU', 'Chengdu Shuangliu'),
    ('DEL', 'Delhi Indira Gandhi'),
    ('DXB', 'Dubai International'),
    ('DOH', 'Doha Hamad'),
    ('SYD', 'Sydney Kingsford Smith'),
    ('MEL', 'Melbourne Tullamarine'),
    ('AKL', 'Auckland'),
    ('SCL', 'Santiago Comodoro Arturo Merino Benítez'),
    ('LIM', 'Lima Jorge Chávez'),
    ('BOG', 'Bogotá El Dorado'),
    ('GRU', 'São Paulo Guarulhos'),
    ('MEX', 'Mexico City Benito Juárez'),
    ('GIG', 'Rio de Janeiro Galeão'),
    ('CCS', 'Caracas Simón Bolívar'),
    ('EZE', 'Buenos Aires Ministro Pistarini'),
    ('BKK', 'Bangkok Suvarnabhumi'),
    ('HKT', 'Phuket'),
    ('CNX', 'Chiang Mai'),
    ('KUL', 'Kuala Lumpur International'),
    ('HAN', 'Hanoi Noi Bai'),
    ('SGN', 'Ho Chi Minh City Tan Son Nhat'),
    ('DPS', 'Denpasar Bali'),
    ('CGK', 'Jakarta Soekarno-Hatta'),
    ('ICN', 'Seoul Incheon'),
    ('GMP', 'Seoul Gimpo'),
    ('TPE', 'Taipei Taoyuan'),
    ('KHH', 'Kaohsiung'),
    ('BOM', 'Mumbai Chhatrapati Shivaji'),
    ('CGO', 'Zhengzhou Xinzheng'),
    ('XMN', 'Xiamen Gaoqi'),
    ('NKG', 'Nanjing Lukou');