-- B737-800
INSERT INTO seats (aircraft_id, row_number, position, location)
VALUES (1, 1, 'A', 'BUSINESS'),
       (1, 1, 'C', 'BUSINESS'),
       (1, 1, 'D', 'BUSINESS'),
       (1, 1, 'F', 'BUSINESS'),
       (1, 2, 'A', 'BUSINESS'),
       (1, 2, 'C', 'BUSINESS'),
       (1, 2, 'D', 'BUSINESS'),
       (1, 2, 'F', 'BUSINESS'),
       (1, 3, 'A', 'BUSINESS'),
       (1, 3, 'C', 'BUSINESS'),
       (1, 3, 'D', 'BUSINESS'),
       (1, 3, 'F', 'BUSINESS'),
       (1, 4, 'A', 'BUSINESS'),
       (1, 4, 'C', 'BUSINESS'),
       (1, 4, 'D', 'BUSINESS'),
       (1, 4, 'F', 'BUSINESS'),
       (1, 5, 'A', 'BUSINESS'),
       (1, 5, 'C', 'BUSINESS'),
       (1, 5, 'D', 'BUSINESS'),
       (1, 5, 'F', 'BUSINESS'),
       (1, 6, 'A', 'WINDOW'),
       (1, 6, 'B', 'FRONT'),
       (1, 6, 'C', 'AISLE'),
       (1, 6, 'D', 'AISLE'),
       (1, 6, 'E', 'FRONT'),
       (1, 6, 'F', 'WINDOW'),
       (1, 7, 'A', 'WINDOW'),
       (1, 7, 'B', 'MIDDLE'),
       (1, 7, 'C', 'AISLE'),
       (1, 7, 'D', 'AISLE'),
       (1, 7, 'E', 'MIDDLE'),
       (1, 7, 'F', 'WINDOW'),
       (1, 8, 'A', 'WINDOW'),
       (1, 8, 'B', 'MIDDLE'),
       (1, 8, 'C', 'AISLE'),
       (1, 8, 'D', 'AISLE'),
       (1, 8, 'E', 'MIDDLE'),
       (1, 8, 'F', 'WINDOW'),
       (1, 9, 'A', 'WINDOW'),
       (1, 9, 'B', 'MIDDLE'),
       (1, 9, 'C', 'AISLE'),
       (1, 9, 'D', 'AISLE'),
       (1, 9, 'E', 'MIDDLE'),
       (1, 9, 'F', 'WINDOW'),
       (1, 10, 'A', 'WINDOW'),
       (1, 10, 'B', 'MIDDLE'),
       (1, 10, 'C', 'AISLE'),
       (1, 10, 'D', 'AISLE'),
       (1, 10, 'E', 'MIDDLE'),
       (1, 10, 'F', 'WINDOW'),
       (1, 11, 'A', 'WINDOW'),
       (1, 11, 'B', 'MIDDLE'),
       (1, 11, 'C', 'AISLE'),
       (1, 11, 'D', 'AISLE'),
       (1, 11, 'E', 'MIDDLE'),
       (1, 11, 'F', 'WINDOW'),
       (1, 12, 'A', 'WINDOW'),
       (1, 12, 'B', 'FRONT'),
       (1, 12, 'C', 'AISLE'),
       (1, 12, 'D', 'AISLE'),
       (1, 12, 'E', 'FRONT'),
       (1, 12, 'F', 'WINDOW'),
       (1, 13, 'A', 'EMERGENCY'),
       (1, 13, 'B', 'EMERGENCY'),
       (1, 13, 'C', 'EMERGENCY'),
       (1, 13, 'D', 'EMERGENCY'),
       (1, 13, 'E', 'EMERGENCY'),
       (1, 13, 'F', 'EMERGENCY'),
       (1, 14, 'A', 'WINDOW'),
       (1, 14, 'B', 'MIDDLE'),
       (1, 14, 'C', 'AISLE'),
       (1, 14, 'D', 'AISLE'),
       (1, 14, 'E', 'MIDDLE'),
       (1, 14, 'F', 'WINDOW'),
       (1, 15, 'A', 'WINDOW'),
       (1, 15, 'B', 'MIDDLE'),
       (1, 15, 'C', 'AISLE'),
       (1, 15, 'D', 'AISLE'),
       (1, 15, 'E', 'MIDDLE'),
       (1, 15, 'F', 'WINDOW'),
       (1, 16, 'A', 'WINDOW'),
       (1, 16, 'B', 'MIDDLE'),
       (1, 16, 'C', 'AISLE'),
       (1, 16, 'D', 'AISLE'),
       (1, 16, 'E', 'MIDDLE'),
       (1, 16, 'F', 'WINDOW'),
       (1, 17, 'A', 'WINDOW'),
       (1, 17, 'B', 'MIDDLE'),
       (1, 17, 'C', 'AISLE'),
       (1, 17, 'D', 'AISLE'),
       (1, 17, 'E', 'MIDDLE'),
       (1, 17, 'F', 'WINDOW'),

       (1, 18, 'A', 'WINDOW'),
       (1, 18, 'B', 'MIDDLE'),
       (1, 18, 'C', 'AISLE'),
       (1, 18, 'D', 'AISLE'),
       (1, 18, 'E', 'MIDDLE'),
       (1, 18, 'F', 'WINDOW'),
       (1, 19, 'A', 'WINDOW'),
       (1, 19, 'B', 'MIDDLE'),
       (1, 19, 'C', 'AISLE'),
       (1, 19, 'D', 'AISLE'),
       (1, 19, 'E', 'MIDDLE'),
       (1, 19, 'F', 'WINDOW'),

       (1, 20, 'A', 'WINDOW'),
       (1, 20, 'B', 'MIDDLE'),
       (1, 20, 'C', 'AISLE' ),
       (1, 20, 'D', 'AISLE' ),
       (1, 20, 'E', 'MIDDLE'),
       (1, 20, 'F', 'WINDOW'),

       (1, 21, 'A', 'WINDOW'),
       (1, 21, 'B', 'MIDDLE'),
       (1, 21, 'C', 'AISLE' ),
       (1, 21, 'D', 'AISLE' ),
       (1, 21, 'E', 'MIDDLE'),
       (1, 21, 'F', 'WINDOW'),

       (1, 22, 'A', 'WINDOW'),
       (1, 22, 'B', 'MIDDLE'),
       (1, 22, 'C', 'AISLE' ),
       (1, 22, 'D', 'AISLE' ),
       (1, 22, 'E', 'MIDDLE'),
       (1, 22, 'F', 'WINDOW'),

       (1, 23, 'A', 'WINDOW'),
       (1, 23, 'B', 'MIDDLE'),
       (1, 23, 'C', 'AISLE' ),
       (1, 23, 'D', 'AISLE' ),
       (1, 23, 'E', 'MIDDLE'),
       (1, 23, 'F', 'WINDOW'),

       (1, 24, 'A', 'WINDOW'),
       (1, 24, 'B', 'MIDDLE'),
       (1, 24, 'C', 'AISLE' ),
       (1, 24, 'D', 'AISLE' ),
       (1, 24, 'E', 'MIDDLE'),
       (1, 24, 'F', 'WINDOW'),

       (1, 25, 'A', 'WINDOW'),
       (1, 25, 'B', 'MIDDLE'),
       (1, 25, 'C', 'AISLE' ),
       (1, 25, 'D', 'AISLE' ),
       (1, 25, 'E', 'MIDDLE'),
       (1, 25, 'F', 'WINDOW'),

       (1, 26, 'A', 'WINDOW'),
       (1, 26, 'B', 'MIDDLE'),
       (1, 26, 'C', 'AISLE' ),
       (1, 26, 'D', 'AISLE' ),
       (1, 26, 'E', 'MIDDLE'),
       (1, 26, 'F', 'WINDOW'),

       (1, 27, 'A', 'WINDOW'),
       (1, 27, 'B', 'MIDDLE'),
       (1, 27, 'C', 'AISLE'),
       (1, 27, 'D', 'AISLE'),
       (1, 27, 'E', 'MIDDLE'),
       (1, 27, 'F', 'WINDOW'),

       (1, 28, 'A', 'WINDOW'),
       (1, 28, 'B', 'MIDDLE'),
       (1, 28, 'C', 'AISLE'),
       (1, 28, 'D', 'AISLE'),
       (1, 28, 'E', 'MIDDLE'),
       (1, 28, 'F', 'WINDOW');