spring:
  datasource:
    url: jdbc:h2:mem:ticketbookingdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  logging:
    level:
      ROOT: INFO
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    url: jdbc:h2:mem:ticketbookingdb
    user: sa
    password:
    enabled: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  data:
    rest:
      base-path: /api-rest
#  mail:
#    host: smtp.yandex.ru
#    port: 25
#    username: testalexandertest
#    password: shuarxibyprcvopn
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#  mail:
#    host: smtp.yandex.ru
#    port: 465
#    username: mymail@gmail.com
#    password: mypassword
#    protocol: smtp
#    tls: true
#    properties.mail.smtp:
#      auth: true
#      starttls.enable: true
#      ssl.trust: smtp.yandex.ru
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${APP_SMTP_USERNAME:TEST_USERNAME}
    password: ${APP_SMTP_PASSWORD:TEST_PASSWORD}
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com

service:
  base-path: "api/v1/"
  bookings-path: "bookings"
  flights-path: "flights"
  schedule-path: "schedule"
  seats-path: "seats"


#  testalexandertest
#  Grks#kGoejMEXG48
# shuarxibyprcvopn
# qdgd cdbp owwd isgs
#  spring.mail.host=smtp.gmail.com
#  spring.mail.port=587
#  spring.mail.username= gmail user name
#  spring.mail.password= your password
#  spring.mail.properties.mail.smtp.auth=true
#  spring.mail.properties.mail.smtp.starttls.enable=true